return {
--    { "vague2k/vague.nvim",               name = "vague",      lazy = true },
--    { "nyoom-engineering/oxocarbon.nvim", name = "oxocarbon",  lazy = true },
--    { "scottmckendry/cyberdream.nvim",    name = "cyberdream", lazy = true },
--    { "yorumicolors/yorumi.nvim",         name = "yorumi",     lazy = true },
--    { "folke/tokyonight.nvim",            name = "tokyonight", lazy = true },
--    {
--        "tiagovla/tokyodark.nvim",
--        name = "tokyodark",
--        priority = 1000,
--        config = function()
--            vim.cmd("colorscheme tokyodark")
--        end,
--        lazy = true
--    },
--    { "alligator/accent.vim", lazy = true },
--    { "catppuccin/nvim",      name = "catppuccin", lazy = true },
--    {
--        "rebelot/kanagawa.nvim",
--        priority = 1000,
--        config = function()
--            -- Default options:
--            require('kanagawa').setup({
--                compile = false,  -- enable compiling the colorscheme
--                undercurl = true, -- enable undercurls
--                commentStyle = { italic = false },
--                functionStyle = {},
--                keywordStyle = { italic = false },
--                statementStyle = { bold = true },
--                typeStyle = {},
--                transparent = false,   -- do not set background color
--                dimInactive = false,   -- dim inactive window `:h hl-NormalNC`
--                terminalColors = true, -- define vim.g.terminal_color_{0,17}
--                colors = {             -- add/modify theme and palette colors
--                    palette = {},
--                    theme = { wave = {}, lotus = {}, dragon = {}, all = {} },
--                },
--                overrides = function(colors) -- add/modify highlights
--                    return {}
--                end,
--                theme = "wave",    -- Load "wave" theme
--                background = {     -- map the value of 'background' option to a theme
--                    dark = "wave", -- try "dragon" !
--                    light = "lotus"
--                },
--            })
--
--            -- setup must be called before loading
--            -- vim.cmd("colorscheme kanagawa")
--        end
--    },
--    { 'jacoborus/tender.vim' },
--    { "kvrohit/rasmus.nvim" },
}
